from datetime import date, datetime
from zoneinfo import ZoneInfo

KST = ZoneInfo("Asia/Seoul")
TODAY = date.today()


def _d(offset: int) -> date:
    from datetime import timedelta
    return date.fromordinal(TODAY.toordinal() + offset)


MOCK_SUBSCRIPTIONS = [
    # 청약 4건
    {
        "title": "해운대 마린시티 더샵 1단지",
        "type": "청약",
        "location": "부산 해운대구 우동",
        "supply_count": 384,
        "price_min": 650_000_000,
        "price_max": 1_150_000_000,
        "application_start": _d(5),
        "application_end": _d(12),
        "source_url": "https://www.applyhome.co.kr/ai/aia/selectAPTLttotPblancListForm.do?houseManageNo=2024000001",
        "is_notified": False,
    },
    {
        "title": "수영구 광안 롯데캐슬",
        "type": "청약",
        "location": "부산 수영구 광안동",
        "supply_count": 215,
        "price_min": 580_000_000,
        "price_max": 980_000_000,
        "application_start": _d(10),
        "application_end": _d(17),
        "source_url": "https://www.applyhome.co.kr/ai/aia/selectAPTLttotPblancListForm.do?houseManageNo=2024000002",
        "is_notified": False,
    },
    {
        "title": "동래구 온천 e편한세상",
        "type": "청약",
        "location": "부산 동래구 온천동",
        "supply_count": 302,
        "price_min": 420_000_000,
        "price_max": 720_000_000,
        "application_start": _d(20),
        "application_end": _d(27),
        "source_url": "https://www.applyhome.co.kr/ai/aia/selectAPTLttotPblancListForm.do?houseManageNo=2024000003",
        "is_notified": False,
    },
    {
        "title": "남구 대연 힐스테이트",
        "type": "청약",
        "location": "부산 남구 대연동",
        "supply_count": 178,
        "price_min": 380_000_000,
        "price_max": 650_000_000,
        "application_start": _d(1),
        "application_end": _d(2),  # 마감임박
        "source_url": "https://www.applyhome.co.kr/ai/aia/selectAPTLttotPblancListForm.do?houseManageNo=2024000004",
        "is_notified": False,
    },
    # 줍줍 2건
    {
        "title": "[무순위] 기장군 정관 자이 무순위",
        "type": "줍줍",
        "location": "부산 기장군 정관면",
        "supply_count": 12,
        "price_min": 310_000_000,
        "price_max": 480_000_000,
        "application_start": _d(0),
        "application_end": _d(3),  # 마감임박
        "source_url": "https://www.applyhome.co.kr/ai/aia/selectAPTLttotPblancListForm.do?houseManageNo=2024000005",
        "is_notified": False,
    },
    {
        "title": "[무순위] 북구 화명 SK뷰 무순위",
        "type": "줍줍",
        "location": "부산 북구 화명동",
        "supply_count": 5,
        "price_min": 290_000_000,
        "price_max": 420_000_000,
        "application_start": _d(8),
        "application_end": _d(14),
        "source_url": "https://www.applyhome.co.kr/ai/aia/selectAPTLttotPblancListForm.do?houseManageNo=2024000006",
        "is_notified": False,
    },
    # 행복주택 2건
    {
        "title": "부산 사하구 괴정 행복주택",
        "type": "행복주택",
        "location": "부산 사하구 괴정동",
        "supply_count": 64,
        "price_min": None,
        "price_max": None,
        "application_start": _d(15),
        "application_end": _d(22),
        "source_url": "https://apply.lh.or.kr/lhapply/apply/wt/wrtanc/selectWtanNoList.do?sc=LH01AA010",
        "is_notified": False,
    },
    {
        "title": "부산 연제구 연산 행복주택",
        "type": "행복주택",
        "location": "부산 연제구 연산동",
        "supply_count": 48,
        "price_min": None,
        "price_max": None,
        "application_start": _d(30),
        "application_end": _d(37),
        "source_url": "https://apply.lh.or.kr/lhapply/apply/wt/wrtanc/selectWtanNoList.do?sc=LH01AA011",
        "is_notified": False,
    },
    # 공공임대 2건
    {
        "title": "부산 금정구 구서 공공임대 (10년)",
        "type": "공공임대",
        "location": "부산 금정구 구서동",
        "supply_count": 120,
        "price_min": None,
        "price_max": None,
        "application_start": _d(45),
        "application_end": _d(52),
        "source_url": "https://apply.lh.or.kr/lhapply/apply/wt/wrtanc/selectWtanNoList.do?sc=LH01AA012",
        "is_notified": False,
    },
    {
        "title": "부산 사상구 주례 영구임대",
        "type": "공공임대",
        "location": "부산 사상구 주례동",
        "supply_count": 80,
        "price_min": None,
        "price_max": None,
        "application_start": _d(60),
        "application_end": _d(67),
        "source_url": "https://apply.lh.or.kr/lhapply/apply/wt/wrtanc/selectWtanNoList.do?sc=LH01AA013",
        "is_notified": False,
    },
]

MOCK_TRANSACTIONS = [
    {"district": "해운대구", "dong": "우동", "apt_name": "마린시티 해운대 아이파크", "area_sqm": 84.9, "floor": 15, "price_won": 1_150_000_000, "deal_date": _d(-5), "build_year": 2011},
    {"district": "해운대구", "dong": "좌동", "apt_name": "해운대 두산위브 더제니스", "area_sqm": 101.2, "floor": 25, "price_won": 980_000_000, "deal_date": _d(-8), "build_year": 2011},
    {"district": "해운대구", "dong": "반여동", "apt_name": "반여 롯데캐슬", "area_sqm": 59.9, "floor": 8, "price_won": 410_000_000, "deal_date": _d(-3), "build_year": 2009},
    {"district": "수영구", "dong": "광안동", "apt_name": "광안 리버빌", "area_sqm": 84.7, "floor": 7, "price_won": 720_000_000, "deal_date": _d(-2), "build_year": 2003},
    {"district": "수영구", "dong": "남천동", "apt_name": "남천 삼익비치타운", "area_sqm": 79.5, "floor": 3, "price_won": 650_000_000, "deal_date": _d(-10), "build_year": 1983},
    {"district": "수영구", "dong": "민락동", "apt_name": "민락 SK뷰", "area_sqm": 59.5, "floor": 12, "price_won": 490_000_000, "deal_date": _d(-6), "build_year": 2006},
    {"district": "동래구", "dong": "온천동", "apt_name": "온천 e편한세상", "area_sqm": 84.9, "floor": 10, "price_won": 560_000_000, "deal_date": _d(-4), "build_year": 2018},
    {"district": "동래구", "dong": "사직동", "apt_name": "사직 동래래미안", "area_sqm": 114.9, "floor": 6, "price_won": 720_000_000, "deal_date": _d(-9), "build_year": 2007},
    {"district": "남구", "dong": "대연동", "apt_name": "대연 힐스테이트", "area_sqm": 59.9, "floor": 4, "price_won": 420_000_000, "deal_date": _d(-7), "build_year": 2020},
    {"district": "남구", "dong": "용호동", "apt_name": "용호 LG메트로시티", "area_sqm": 84.9, "floor": 18, "price_won": 620_000_000, "deal_date": _d(-11), "build_year": 2005},
    {"district": "사하구", "dong": "괴정동", "apt_name": "괴정 대림아파트", "area_sqm": 59.5, "floor": 5, "price_won": 270_000_000, "deal_date": _d(-3), "build_year": 1998},
    {"district": "사하구", "dong": "당리동", "apt_name": "당리 주공", "area_sqm": 46.2, "floor": 2, "price_won": 195_000_000, "deal_date": _d(-14), "build_year": 1992},
    {"district": "북구", "dong": "화명동", "apt_name": "화명 SK뷰", "area_sqm": 84.9, "floor": 9, "price_won": 430_000_000, "deal_date": _d(-5), "build_year": 2015},
    {"district": "북구", "dong": "만덕동", "apt_name": "만덕 현대아파트", "area_sqm": 59.9, "floor": 7, "price_won": 280_000_000, "deal_date": _d(-13), "build_year": 2002},
    {"district": "기장군", "dong": "정관면", "apt_name": "정관 자이", "area_sqm": 84.9, "floor": 11, "price_won": 380_000_000, "deal_date": _d(-2), "build_year": 2016},
    {"district": "기장군", "dong": "일광면", "apt_name": "일광 신도시 한신더휴", "area_sqm": 59.9, "floor": 6, "price_won": 310_000_000, "deal_date": _d(-8), "build_year": 2019},
    {"district": "연제구", "dong": "연산동", "apt_name": "연산 롯데캐슬", "area_sqm": 84.9, "floor": 13, "price_won": 520_000_000, "deal_date": _d(-6), "build_year": 2012},
    {"district": "금정구", "dong": "구서동", "apt_name": "구서 현대아이파크", "area_sqm": 59.9, "floor": 5, "price_won": 340_000_000, "deal_date": _d(-10), "build_year": 2010},
    {"district": "부산진구", "dong": "전포동", "apt_name": "전포 두산위브", "area_sqm": 59.5, "floor": 8, "price_won": 380_000_000, "deal_date": _d(-4), "build_year": 2013},
    {"district": "부산진구", "dong": "부전동", "apt_name": "서면 에일린의뜰", "area_sqm": 84.9, "floor": 20, "price_won": 620_000_000, "deal_date": _d(-7), "build_year": 2021},
    {"district": "중구", "dong": "영주동", "apt_name": "영주 센트럴파크", "area_sqm": 59.9, "floor": 10, "price_won": 310_000_000, "deal_date": _d(-9), "build_year": 2017},
    {"district": "서구", "dong": "서대신동", "apt_name": "서대신 한신더휴", "area_sqm": 59.9, "floor": 4, "price_won": 260_000_000, "deal_date": _d(-11), "build_year": 2008},
    {"district": "동구", "dong": "범일동", "apt_name": "범일 현대홈타운", "area_sqm": 59.5, "floor": 6, "price_won": 230_000_000, "deal_date": _d(-15), "build_year": 2000},
    {"district": "영도구", "dong": "신선동", "apt_name": "신선 SK", "area_sqm": 46.2, "floor": 3, "price_won": 180_000_000, "deal_date": _d(-12), "build_year": 1995},
    {"district": "강서구", "dong": "명지동", "apt_name": "명지 오션시티 푸르지오", "area_sqm": 84.9, "floor": 7, "price_won": 420_000_000, "deal_date": _d(-3), "build_year": 2018},
    {"district": "사상구", "dong": "주례동", "apt_name": "주례 e편한세상", "area_sqm": 59.9, "floor": 9, "price_won": 290_000_000, "deal_date": _d(-6), "build_year": 2016},
    {"district": "수영구", "dong": "수영동", "apt_name": "수영 한화포레나", "area_sqm": 84.9, "floor": 14, "price_won": 680_000_000, "deal_date": _d(-1), "build_year": 2022},
    {"district": "해운대구", "dong": "송정동", "apt_name": "송정 힐스테이트", "area_sqm": 59.9, "floor": 8, "price_won": 430_000_000, "deal_date": _d(-5), "build_year": 2020},
    {"district": "동래구", "dong": "낙민동", "apt_name": "낙민 래미안", "area_sqm": 84.9, "floor": 5, "price_won": 540_000_000, "deal_date": _d(-8), "build_year": 2014},
    {"district": "금정구", "dong": "장전동", "apt_name": "장전 부산대 롯데", "area_sqm": 59.9, "floor": 3, "price_won": 360_000_000, "deal_date": _d(-4), "build_year": 2009},
]

MOCK_NEWS = [
    {
        "title": "해운대 센텀2지구 개발계획 확정…부산 부동산 호재 기대",
        "summary": "- 해운대 센텀2지구 개발이 확정되어 인근 아파트 가격 상승 기대감이 높아지고 있습니다.\n- 총 1조 5천억 규모의 개발로 상업·주거 복합단지가 조성될 예정입니다.\n- 매수 희망자에게는 해운대구 일대 투자 적기로 분석됩니다.",
        "source_url": "https://news.naver.com/article/mock/001",
        "source_type": "뉴스",
        "sentiment": "positive",
        "sentiment_score": 0.85,
        "published_at": datetime(_d(-1).year, _d(-1).month, _d(-1).day, 9, 0, tzinfo=KST),
    },
    {
        "title": "부산 GTX 노선 확정, 수영구·동래구 수혜 예상",
        "summary": "- 부산 광역급행철도(GTX) 노선이 확정되어 수영구·동래구 일대 교통 접근성이 크게 개선됩니다.\n- 역세권 아파트 가격 상승 기대로 매수 문의가 증가하고 있습니다.\n- 실수요자 입장에서는 지금이 선점 기회가 될 수 있습니다.",
        "source_url": "https://news.naver.com/article/mock/002",
        "source_type": "뉴스",
        "sentiment": "positive",
        "sentiment_score": 0.78,
        "published_at": datetime(_d(-2).year, _d(-2).month, _d(-2).day, 10, 30, tzinfo=KST),
    },
    {
        "title": "부산 북항 재개발 2단계 착공…원도심 르네상스 기대",
        "summary": "- 부산 북항 재개발 2단계가 착공되어 동구·중구 원도심 재생에 속도가 붙고 있습니다.\n- 상업·문화 복합시설과 함께 고급 주거시설도 공급될 예정입니다.\n- 장기적으로 원도심 아파트 가격 상승 모멘텀으로 작용할 것으로 보입니다.",
        "source_url": "https://blog.naver.com/mock/003",
        "source_type": "블로그",
        "sentiment": "positive",
        "sentiment_score": 0.72,
        "published_at": datetime(_d(-3).year, _d(-3).month, _d(-3).day, 14, 0, tzinfo=KST),
    },
    {
        "title": "생애최초 특별공급 확대…부산 청약 당첨 기회 넓어진다",
        "summary": "- 정부가 생애최초 특별공급 비율을 기존 20%에서 30%로 확대합니다.\n- 부산 신규 분양 단지 청약 시 생애최초 신청자에게 유리한 환경이 조성됩니다.\n- 무주택 실수요자라면 이번 청약 시즌을 적극 활용할 것을 권장합니다.",
        "source_url": "https://blog.naver.com/mock/004",
        "source_type": "블로그",
        "sentiment": "positive",
        "sentiment_score": 0.80,
        "published_at": datetime(_d(-4).year, _d(-4).month, _d(-4).day, 11, 0, tzinfo=KST),
    },
    {
        "title": "부산 아파트 미분양 3개월 연속 증가…시장 침체 우려",
        "summary": "- 부산 미분양 아파트가 3개월 연속 증가해 시장 침체에 대한 우려가 커지고 있습니다.\n- 사하구·북구 등 외곽 지역을 중심으로 미분양이 집중되는 양상입니다.\n- 매수 타이밍을 고민 중이라면 시장 상황을 좀 더 지켜볼 필요가 있습니다.",
        "source_url": "https://news.naver.com/article/mock/005",
        "source_type": "뉴스",
        "sentiment": "negative",
        "sentiment_score": 0.74,
        "published_at": datetime(_d(-2).year, _d(-2).month, _d(-2).day, 16, 0, tzinfo=KST),
    },
    {
        "title": "부산 전셋값 하락세 지속…역전세 우려 확산",
        "summary": "- 부산 전세 시장이 5개월째 하락세를 이어가며 역전세 위험이 높아지고 있습니다.\n- 해운대·수영구 고가 전세 단지에서 보증금 반환 분쟁이 늘고 있습니다.\n- 전세 계약 시 HUG 보증보험 가입을 반드시 확인하시기 바랍니다.",
        "source_url": "https://news.naver.com/article/mock/006",
        "source_type": "뉴스",
        "sentiment": "negative",
        "sentiment_score": 0.68,
        "published_at": datetime(_d(-5).year, _d(-5).month, _d(-5).day, 9, 0, tzinfo=KST),
    },
    {
        "title": "DSR 규제 강화 예고…대출 한도 축소 전망",
        "summary": "- 금융당국이 DSR 규제를 추가 강화하는 방안을 검토 중입니다.\n- 실행 시 부산 중저가 아파트 수요자의 대출 한도가 최대 10% 감소할 수 있습니다.\n- 매수를 계획 중이라면 규제 확정 전 대출 상담을 미리 진행하는 것이 좋습니다.",
        "source_url": "https://blog.naver.com/mock/007",
        "source_type": "블로그",
        "sentiment": "negative",
        "sentiment_score": 0.71,
        "published_at": datetime(_d(-6).year, _d(-6).month, _d(-6).day, 13, 0, tzinfo=KST),
    },
    {
        "title": "부산 아파트 거래량 전월 대비 소폭 회복",
        "summary": "- 부산 아파트 거래량이 전월 대비 8% 증가하며 소폭 회복세를 보이고 있습니다.\n- 회복세가 뚜렷하지 않아 시장 방향성을 단정하기는 이른 상황입니다.\n- 매수·매도 양측 모두 관망세가 지속되고 있습니다.",
        "source_url": "https://news.naver.com/article/mock/008",
        "source_type": "뉴스",
        "sentiment": "neutral",
        "sentiment_score": 0.52,
        "published_at": datetime(_d(-3).year, _d(-3).month, _d(-3).day, 10, 0, tzinfo=KST),
    },
    {
        "title": "부산 재건축 안전진단 기준 완화 검토",
        "summary": "- 정부가 재건축 안전진단 기준 완화를 검토 중이며 부산 노후 아파트 단지가 주목받고 있습니다.\n- 동래구·남구 등 1980~90년대 아파트 단지에 영향이 클 것으로 예상됩니다.\n- 구체적인 완화 폭은 아직 미정으로 추가 발표를 기다릴 필요가 있습니다.",
        "source_url": "https://blog.naver.com/mock/009",
        "source_type": "블로그",
        "sentiment": "neutral",
        "sentiment_score": 0.55,
        "published_at": datetime(_d(-7).year, _d(-7).month, _d(-7).day, 15, 0, tzinfo=KST),
    },
    {
        "title": "2026년 부산 신규 분양 물량 전년 대비 12% 증가 예정",
        "summary": "- 2026년 부산 신규 분양 예정 물량이 전년 대비 12% 증가한 2만 6천 가구로 집계됩니다.\n- 해운대·기장 등 동부산 권역 공급이 집중될 예정입니다.\n- 공급 증가가 가격에 미칠 영향은 수요 흡수력에 달려 있어 면밀한 관찰이 필요합니다.",
        "source_url": "https://blog.naver.com/mock/010",
        "source_type": "블로그",
        "sentiment": "neutral",
        "sentiment_score": 0.50,
        "published_at": datetime(_d(-8).year, _d(-8).month, _d(-8).day, 11, 0, tzinfo=KST),
    },
]

# 부산 16개 구·군 시세 통계
MOCK_MARKET_STATS = [
    {"district": "해운대구", "avg_price": 820_000_000, "avg_jeonse_price": 460_000_000, "jeonse_rate": 0.56, "unsold_count": 12,  "transaction_volume": 145, "stat_date": TODAY},
    {"district": "수영구",   "avg_price": 680_000_000, "avg_jeonse_price": 400_000_000, "jeonse_rate": 0.59, "unsold_count": 5,   "transaction_volume": 98,  "stat_date": TODAY},
    {"district": "동래구",   "avg_price": 560_000_000, "avg_jeonse_price": 350_000_000, "jeonse_rate": 0.63, "unsold_count": 8,   "transaction_volume": 112, "stat_date": TODAY},
    {"district": "남구",     "avg_price": 490_000_000, "avg_jeonse_price": 320_000_000, "jeonse_rate": 0.65, "unsold_count": 15,  "transaction_volume": 87,  "stat_date": TODAY},
    {"district": "연제구",   "avg_price": 480_000_000, "avg_jeonse_price": 315_000_000, "jeonse_rate": 0.66, "unsold_count": 6,   "transaction_volume": 74,  "stat_date": TODAY},
    {"district": "부산진구", "avg_price": 460_000_000, "avg_jeonse_price": 310_000_000, "jeonse_rate": 0.67, "unsold_count": 20,  "transaction_volume": 130, "stat_date": TODAY},
    {"district": "금정구",   "avg_price": 370_000_000, "avg_jeonse_price": 255_000_000, "jeonse_rate": 0.69, "unsold_count": 10,  "transaction_volume": 95,  "stat_date": TODAY},
    {"district": "기장군",   "avg_price": 380_000_000, "avg_jeonse_price": 270_000_000, "jeonse_rate": 0.71, "unsold_count": 35,  "transaction_volume": 88,  "stat_date": TODAY},
    {"district": "북구",     "avg_price": 340_000_000, "avg_jeonse_price": 240_000_000, "jeonse_rate": 0.71, "unsold_count": 18,  "transaction_volume": 76,  "stat_date": TODAY},
    {"district": "강서구",   "avg_price": 350_000_000, "avg_jeonse_price": 255_000_000, "jeonse_rate": 0.73, "unsold_count": 42,  "transaction_volume": 62,  "stat_date": TODAY},
    {"district": "사상구",   "avg_price": 290_000_000, "avg_jeonse_price": 205_000_000, "jeonse_rate": 0.71, "unsold_count": 22,  "transaction_volume": 58,  "stat_date": TODAY},
    {"district": "사하구",   "avg_price": 270_000_000, "avg_jeonse_price": 195_000_000, "jeonse_rate": 0.72, "unsold_count": 28,  "transaction_volume": 65,  "stat_date": TODAY},
    {"district": "중구",     "avg_price": 310_000_000, "avg_jeonse_price": 215_000_000, "jeonse_rate": 0.69, "unsold_count": 3,   "transaction_volume": 32,  "stat_date": TODAY},
    {"district": "서구",     "avg_price": 260_000_000, "avg_jeonse_price": 185_000_000, "jeonse_rate": 0.71, "unsold_count": 7,   "transaction_volume": 41,  "stat_date": TODAY},
    {"district": "동구",     "avg_price": 240_000_000, "avg_jeonse_price": 175_000_000, "jeonse_rate": 0.73, "unsold_count": 9,   "transaction_volume": 38,  "stat_date": TODAY},
    {"district": "영도구",   "avg_price": 210_000_000, "avg_jeonse_price": 155_000_000, "jeonse_rate": 0.74, "unsold_count": 14,  "transaction_volume": 29,  "stat_date": TODAY},
]
